### PR TITLE
Better autocomplete by supporting all visible modules

### PR DESCRIPTION
**Pull request by sadovnychyi**
- Handle all python modules which are visible to file you are currently editing.
- Replace tabs with spaces in python code as tabs are forbidden by PEP8.
- Handle multiple folder projects (but its useless if project folder is not a python module, see TODO comment)

### CODE REVIEW

**Comment by sadovnychyi** [comment]
Some explanations:

First I've passed a file path of the file you're editing to the JEDI. After this imports from current module became visible for autocompletion, but if you're in submodule -- it will not see parent modules.

That's why I've used `_get_top_level_module` method which will look for top level module and add it to the sys.path.

So, even if you open a file which is not in the project you're working in -- it will work anyway!

Now thats a question if we should pass project folders to JEDI or not?

**Comment by sadovnychyi** [comment]
Don't append extra dot on imports:

sample

**Comment by sadovnychyi** [comment]
Use full completion provided by JEDI:

When you type `string` and select `StringIO` as a completion -- you will get stringIO, which is wrong.
instead, we should replace the whole method with name provided by JEDI.

**Comment by tinloaf** [comment]
I'm not sure the 'use full completion provided by Jedi' is the right thing to do. I have experienced some problems with that, when the prefix was longer than what jedi returned.. I'll have to play around a bit with this one.

**Comment by sadovnychyi** [comment]
Ok, I removed this commit. Is everything else looks good for you?
Can you give a sample when the prefix is longer so I can play with it as well?

**Comment by tinloaf** [comment]
I'm currently thinking about the bigger picture of this. Here's what I think I'll do (and which will conflict with this PR a bit):
- For every editor (i.e. every tab / open file), dynamically create a list of paths to be added to the PYTHONPATH. This will consist of:
  - The path that atom thinks is the project
  - The path that we arrive at if we ascend, starting with the file itself, all directories containing an init.py
  - Any site-packages directory indicated by the virtualenv package
- Then, for every set of those paths (most of the time, many files / editors will hopefully belong to the same project and share the same set of paths), create a separate jedi-cmd process that adds these paths to the pythonpath.

Any comments on this?

**Pull request closed without merging**
